# Generated by Django 5.2.8 on 2025-12-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': {('Gestionar_prestamos', 'Puede_gestionar_prestamos'), ('Ver_prestamos', 'Puede_ver_prestamos')}},
        ),
    ]
