# Generated by Django 5.2.8 on 2025-12-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_libro_image_alter_multa_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
