# Generated by Django 5.2.8 on 2025-12-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_autor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='imagen',
        ),
    ]
