# Generated by Django 5.2.8 on 2026-01-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_image_autor_imagen_rename_image_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
    ]
