# Generated by Django 5.2.8 on 2026-01-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_autor_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'permissions': {('Gestionar_autores', 'Puede_gestionar_autores'), ('Ver_autores', 'Puede_ver_autores')}},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'permissions': {('Gestionar_libros', 'Puede_gestionar_libros'), ('Ver_libros', 'Puede_ver_libros')}},
        ),
        migrations.AlterModelOptions(
            name='multa',
            options={'permissions': {('Gestionar_multas', 'Puede_gestionar_multas'), ('Ver_multas', 'Puede_ver_multas')}},
        ),
    ]
