# Generated by Django 5.2.8 on 2026-01-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_autor_options_alter_libro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamos', to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SolicitudPrestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': {('Gestionar_solicitudes_prestamos', 'Puede_gestionar_solicitudes_prestamos'), ('Ver_solicitudes_prestamos', 'Puede_ver_solicitudes_prestamos')},
            },
        ),
    ]
