# Generated by Django 5.2.8 on 2026-01-05 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_solicitudprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
