# Generated by Django 5.2.8 on 2026-01-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_solicitudprestamo_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudprestamo',
            options={'permissions': {('Gestionar_solicitudes_prestamos', 'Puede_gestionar_solicitudes_prestamos'), ('Solicitar_prestamos', 'Puede_solicitar_prestamos'), ('Ver_solicitudes_prestamos', 'Puede_ver_solicitudes_prestamos')}},
        ),
    ]
