# Generated by Django 5.2.8 on 2026-01-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_historicalautor_historicallibro_historicalmulta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': {('Gestionar_prestamos', 'Puede_gestionar_prestamos'), ('Ver_auditoria_global', 'Puede ver la auditoría global del sistema'), ('Ver_prestamos', 'Puede_ver_prestamos')}},
        ),
    ]
