"""
Django settings for Django_ruilova project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent #EXPLICAER QE ES BASE DIR

TITLE = "UTE 2 semestre" #aca ponemos el titulo de la pagina web apra que este desarollo sirva para cualquier otro desarollo
#ES DECIR, CUALQUIER PERSONA SOLO CAMBIA EL SETTINGS Y YA SE REFLEJA EN TODA LA PAGINA


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h)ry2e)7-ppto-^tf__n(y@5&02@q#xg!na_yha$3_#0vuzwbo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #lo desactivamos ya 

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'bibliotecaimperial.com', 'www.bibliotecaimperial.com' ]

#redirecciones
LOGIN_REDIRECT_URL = "index"

LOGIN_URL = 'login'

#logout?
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
    'django_extensions' #este es para unas extensiones utiles, lo use para refrescar un permiso que no se cambiaba correctamente
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_ruilova.urls'

TEMPLATES = [  #HAY QUE DECIR QUE DIRECTORIOS DEB E BUSCAR LAS TEMPLATES, COMO CREAMOS EL GESTION TEMPLATES HAY QUE AVISARLE, ACA HAY QUE USAR
    #LA VARIABLE BASE DIR QUE ESA POR ARRIBA, EXPLICAR Y INVESTIGAR ESTO
    #QUE HACE BASE DIR
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', #POR DEFECTO DONDE ESTA EL BACK ENDR
        'DIRS': [BASE_DIR], #aca hay que poner BASE DIR PARA QUE VEA QUE LOS DIRS SON LOS QUE ESTAN EN BASE DIRS, EXPLICAR, PERO EL BASE DIR
    #COMO SACA LA DIRECCION DEL DJANGO YA TIENE ACCESO A TODO
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_ruilova.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' #nuestro dominio slash static
MEDIA_URL = '/media/' #los archivos multimedia se graban aca
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static') #EXPLICAR ESTE CACHITO DE CODIGO DE ACA
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
